- name:   Disable iptables
  service: name=iptables state=stopped enabled=no

- name:   Stop SELinux
  shell: setenforce 0
  ignore_errors: True

- name:   Disable SELinux
  lineinfile: dest=/etc/sysconfig/selinux regexp="^SELINUX=.*" line="SELINUX=disabled"
- name:   Create /etc/hosts file
  template: src=hosts.j2 dest=/etc/hosts mode=0644

