- name:   Disable iptables
  service: name=iptables state=stopped enabled=no

- name:   Install libselinux-python package
  yum: name=libselinux-python state=latest  

- name:   Disable SELinux
  selinux: state=disabled

- name:   Restart machine
  shell: shutdown -r now "Ansible updates triggered"

- name:   Waiting for server to come back
  local_action: wait_for host={{ inventory_hostname }} state=started timeout=120
  sudo: no

#- name:   Stop SELinux
#  shell: setenforce 0

#- name:   Disable SELinux
#  lineinfile: dest=/etc/sysconfig/selinux regexp="^SELINUX=.*" line="SELINUX=disabled"

#- name:   Copy ssh public key
#  copy: src=.ssh/id_rsa.pub dest=/tmp/id_rsa.pub
#  sudo: no

#- name:   Append authorized_keys
#  shell: cat /tmp/id_rsa.pub >> ~/.ssh/authorized_keys
#  sudo: no

