- name:   Comment out setting related network bridge of libvirt in kernel parameter
  shell: cp -f /etc/sysctl.conf /etc/sysctl.conf.org && sed -e s/^net.bridge.bridge-nf-call/#net.bridge.bridge-nf-call/g /etc/sysctl.conf.org > /etc/sysctl.conf && rm -f /etc/sysctl.conf.org

- name:   Set kernel parameter about swappiness
  shell: echo "vm.swappiness=0" >> /etc/sysctl.conf && sysctl -p

